# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Package

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci
  release:
    types:
      - created

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: echo "Installing dependencies"
    
    - name: Package
      run: zip -r -FS com.github.juliencombattelli.caVaEtreToutNoir.plasmoid ./package/
    
    - name: Upload commit assets
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        path: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
        name: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
    - name: Get release url
      if: ${{ github.event_name == 'release' }}
      id: get_release
      uses: bruceadams/get-release@v1.2.0
    - name: Upload release assets
      if: ${{ github.event_name == 'release' }}
      run: echo "ref ${GITHUB_REF##*/}, url ${{ steps.get_release.outputs.upload_url }}"
      
