# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Package

on: [push, pull_request, release]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo "Installing dependencies"
    - name: Package
      run: zip -r -FS com.github.juliencombattelli.caVaEtreToutNoir.plasmoid ./package/
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
        name: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
