name: Package

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  package:

    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PLASMOID_NAME: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
      ARTIFACT_NAME: theme-switcher.zip
      ARTIFACT_TYPE: application/zip

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo npm install --global web-ext
    
    - name: Package artifacts
      run: ./package-artifacts.sh -i ${{ secrets.AMO_JWT_ISSUER }} -s ${{ secrets.AMO_JWT_SECRET }} -p ${{ env.PLASMOID_NAME }} -a ${{ env.ARTIFACT_NAME }}
    
    - name: Upload commit assets
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.ARTIFACT_NAME }}
        name: ${{ env.ARTIFACT_NAME }}
    
    - name: Get release url
      if: ${{ github.event_name == 'release' }}
      id: get_release
      uses: bruceadams/get-release@v1.2.0
      
    - name: Upload release assets
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ env.ARTIFACT_NAME }}
        asset_name: ${{ env.ARTIFACT_NAME }}
        asset_content_type: ${{ env.ARTIFACT_TYPE }}
      
