# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Package

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci
  release:
    types:
      - created

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: echo "Installing dependencies"
    
    - name: Package
      run: zip -r -FS com.github.juliencombattelli.caVaEtreToutNoir.plasmoid ./package/
    
    - name: Upload commit assets
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        path: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
        name: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
    
    - name: Upload release assets
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://github.com/juliencombattelli/plasma-applet-ca-va-etre-tout-noir/releases/tag/${{ GITHUB_REF  }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
        asset_name: com.github.juliencombattelli.caVaEtreToutNoir.plasmoid
        asset_content_type: application/zip
